### ISSUE TITLE
Error: Language supported but model not found

### ISSUE THREAD

**Issue by rsirel** [EMBEDDIA/ULR_NER_REST#2]
```
Traceback (most recent call last):
  File \"/usr/src/app/project/NER_API.py\", line 120, in post
    json_output = rpyc.classic.obtain(NER_service.root.processNERRequest(language, data_set))
  File \"/usr/local/lib/python3.8/site-packages/rpyc/core/netref.py\", line 253, in _call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File \"/usr/local/lib/python3.8/site-packages/rpyc/core/netref.py\", line 76, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File \"/usr/local/lib/python3.8/site-packages/rpyc/core/protocol.py\", line 469, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File \"/usr/local/lib/python3.8/site-packages/rpyc/core/async.py\", line 102, in value
    raise self._obj
_get_exception_class.<locals>.Derived: Language supported but model not found

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File \"/opt/conda/envs/ner_service/lib/python3.6/site-packages/rpyc/core/protocol.py\", line 320, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File \"/opt/conda/envs/ner_service/lib/python3.6/site-packages/rpyc/core/protocol.py\", line 593, in _handle_call
    return obj(*args, **dict(kwargs))
  File \"NERService.py\", line 158, in exposed_processNERRequest
    raise e
  File \"NERService.py\", line 154, in exposed_processNERRequest
    model = NERService.__NER_instance.getModel(language)
  File \"NERService.py\", line 128, in getModel
    raise Exception(\"Language supported but model not found\")
Exception: Language supported but model not found

"
```
Using Docker. All required models are downloaded. Fresh build from the repo.

**Comment by creat89** [comment]
Hello,
I have tested the docker container, the one previous accepting your changes, and everything runs fine. Are you sure the changes that you proposed did not affect the loading of the models? Because I'm sure the error comes modifications done in the paths in the docker-compose file and config files:

Seeing the container I can see that there is some kind of duplicated files:
![image](https://user-images.githubusercontent.com/17121539/144491657-223059c5-dd30-40af-b57f-924860dc7e26.png)
As you can see in the ulr_ner_rest-ner-1:/data/embeddings there is nothing downloaded

However in ulr_ner_rest-ner-1:/ner_service/embeddings you can notice that the embeddings (BERT and FastText) are found there:

![image](https://user-images.githubusercontent.com/17121539/144491863-eb1e56ef-4973-4631-ad91-e39bb3f3bf38.png)

And I have stopped the contained before:

![image](https://user-images.githubusercontent.com/17121539/144492207-b9b5535b-bdbe-4a94-9bc5-6bc1882faa46.png)

And the embeddings that I downloaded before are there. They did not vanished.

So, while I originally accepted the changes that you proposed, the code seems to work perfectly.

![image](https://user-images.githubusercontent.com/17121539/144492430-49eae0a3-19d3-4d50-92c8-947c32c462e3.png)

Thus, I'm guessing that you use a modified version of the code in order to improve the quality of the docker. And that the changes done in the paths are the ones that affected the system finding the models. I hope that the images that I attached could give you an idea of what you and I did wrong. In the sense, that I'm sure that certain files shouldn't be duplicated (my mistake) and why your paths are wrong (?).

**Comment by creat89** [comment]
And just to make it clear, why it shows that I had a modified file in the branch:
![image](https://user-images.githubusercontent.com/17121539/144495249-7bb342b7-a4f4-425e-a176-474cd990805a.png)
While I downloaded all the FastText models, in order to test docker in my laptop I had to reduce the number of models to load as I don't have huge amounts of RAM. In this case, I chose Russian. Otherwise, the code was the same.

**Comment by rsirel** [comment]
Unless the paths are changed, the models are downloaded on each container startup. In the latest commit to refactor branch I got everything working. The mount logic was flawed and the models were saved inside the container and not the mount.

**Comment by creat89** [comment]
The models will be downloaded on each container startup if the files are incomplete or did not finish the download. But otherwise, if I run `docker-compose up` the downloaded models are there:

![image](https://user-images.githubusercontent.com/17121539/144570263-ecd692a7-ac6e-42bf-9e2e-6f2c3c4c2db6.png)

It might look that the models are being tried to be donwloaded, but in fact the bash file is checking that everything was downloaded and unzip. I don't know if that was the issue.

I might be using the wrong command to do the startup, that could be possible.

I will check your branch, but if you could guide me on which is the command that was breaking the downloaded files it could be great.

**Comment by rsirel** [comment]
I think the main problem was that all of the embeddings were downloaded into the same directories as the scripts and this actually made it to run each time. For that reason I added the "data" folder inside ner_service directory - it will only contain the downloaded models. Important is to mount the "ner_service/data" so it will be using a volume for the downloadable models. With that i got the startup time from ~30mins to 2 mins.

Also I have no idea why the model loading (not downloading) failed before. It seems to be working now tho :)

**Comment by creat89** [comment]
I will close the issue then, I'll check your branch during the weekend and merge it later. If there is another issue, don't hesitate in opening another issue or reopening this one.

**Comment by rsirel** [comment]
Sure, but there still might be stuff I missed as I'm not too familiar with the code. For one I saw the vocab file for BERT being downloaded still each time. It's a small issue, but that hints there is still some small flaw in the mount/download logic.
